/// Enumeration of Chat Message Roles.
library;

/// Represents the sender role of a chat message in the AI workspace.
enum MessageRole {
  /// Message authored by the human end user.
  user,

  /// Message generated by the AI assistant / LLM model.
  assistant,

  /// System prompt or instructions guiding LLM context behavior.
  system,

  /// Tool execution result or agent function response.
  tool;

  /// Whether this message was authored by the user.
  bool get isUser => this == MessageRole.user;

  /// Whether this message was generated by the AI assistant.
  bool get isAssistant => this == MessageRole.assistant;

  /// Whether this message represents a system prompt.
  bool get isSystem => this == MessageRole.system;
}
